---
- name: Allocating elastic IP to instance
  hosts: localhost
  connection: local
  vars_files:
  - [var.yml]
  tasks:
  - name: started
    ec2_eip:
       aws_access_key: "{{aws_access_key}}"
       aws_secret_key: "{{aws_secret_key}}"
       in_vpc: yes
       reuse_existing_ip_allowed: yes
       state: present
       region: eu-west-1
       device_id: i-0ce2fc1242b26ce20
    register: instance_eip
  - debug: var=instance_eip.public_ip
