---
- name: upload file to s3 bucket
  hosts: localhost
  connection: local
  vars_files:
  - [var.yml]
  tasks:
  - name: uploading file
    aws_s3:
     bucket: ansiblebucketcoe
     object: /vmimages/Node2-disk1.vmdk
     src: /home/automation/ajishaws/ansibleaws_files/Demo/Node2-disk1.vmdk
     mode: put
     encrypt: True
     aws_access_key: "{{aws_access_key}}"
     aws_secret_key: "{{aws_secret_key}}"

